### ISSUE TITLE
How can clean image cache ? 

### ISSUE THREAD

**Issue by ghost** [WishWei/WXCycleScrollView#1]
Hey, the problem is this way
I uploaded a photo to my server called "01.jpg"
This time to open my project, you can download to this picture
At this point I upload a picture, overwrite this "01.jp"
At this time to re-open the App, download the picture is still the first upload goes

I suspect that you use the package to the "sdwebimage"
So he seems to have the function of caching photos
How can I turn it off in Swift?

**Comment by ghost** [comment]
Stupid I found a way :)

Step 1: import SDWebImage

Step 2: SDImageCache.shared (). ClearMemory ()
            SDImageCache.shared (). ClearDisk (onCompletion: nil)

Done

**Comment by WishWei** [comment]
the pic cache is managed by SDWebCache

**Comment by WishWei** [comment]
web image is managed by SDWebImage.
